#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("_1031_Calculator.Resource", IsApplication=true)]

namespace _1031_Calculator
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050002
			public const int marital_status = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int married_income = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int married_income_tax_rate = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int single_income = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int single_income_tax_rate = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int state_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int state_tax = 2131034113;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int myButton = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int oval = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06001a
			public const int DataHeader = 2131099674;
			
			// aapt resource value: 0x7f060018
			public const int DataRow = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int DataValue = 2131099673;
			
			// aapt resource value: 0x7f060001
			public const int GridLayoutCalculator = 2131099649;
			
			// aapt resource value: 0x7f060017
			public const int calculate = 2131099671;
			
			// aapt resource value: 0x7f060000
			public const int expandableListview = 2131099648;
			
			// aapt resource value: 0x7f06001b
			public const int fragmentContainer = 2131099675;
			
			// aapt resource value: 0x7f06000a
			public const int ipCapitalImprovements = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int ipPurchasePrice = 2131099655;
			
			// aapt resource value: 0x7f06000d
			public const int ipSalePrice = 2131099661;
			
			// aapt resource value: 0x7f060008
			public const int lblCapitalImprovements = 2131099656;
			
			// aapt resource value: 0x7f060012
			public const int lblIncome = 2131099666;
			
			// aapt resource value: 0x7f060010
			public const int lblMaritalStatus = 2131099664;
			
			// aapt resource value: 0x7f060005
			public const int lblPurchasePrice = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int lblSalePrice = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int lblSelectState = 2131099662;
			
			// aapt resource value: 0x7f060002
			public const int percentagecomplete = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int percentagetax = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int saveresults = 2131099652;
			
			// aapt resource value: 0x7f060009
			public const int seekCapitalImprovements = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int seekPurchasePrice = 2131099654;
			
			// aapt resource value: 0x7f06000c
			public const int seekSalePrice = 2131099660;
			
			// aapt resource value: 0x7f060013
			public const int spinnerIncome = 2131099667;
			
			// aapt resource value: 0x7f060011
			public const int spinnerMaritalStatus = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int spinnerStates = 2131099663;
			
			// aapt resource value: 0x7f060015
			public const int textHOLM1 = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int textHOLM2 = 2131099670;
			
			// aapt resource value: 0x7f060014
			public const int textSponsoredBy = 2131099668;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About1031 = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Calculator1031 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DataListItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Disclaimer = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ListGroup = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SavedProperties = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int About1031 = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Calculator1031 = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int Disclaimer = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int SavedProperties = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
